#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
psur_generator.py — PSUR/PBRER 自动报告生成

P1 升级（2026-08-16，v0.1.38），基于 CIOMS PSUR / ICH E2C(R2) PBRER 标准格式。
生成 Markdown 格式的 PSUR 章节。

Usage:
  python scripts/psur_generator.py --signals signals.json --period "2025-Q1" --format md
  python scripts/psur_generator.py --signals signals.json --period "2025" --format json
"""

import argparse
import datetime
import json
import os
import sys
from typing import Dict, List, Optional


# PSUR 标准结构（基于 CIOMS / ICH E2C(R2)）
PSUR_TEMPLATE = """# PSUR — 定期安全性更新报告 / Periodic Safety Update Report

**报告期间 / Reporting Period**: {period}
**生成日期 / Generated**: {generated_date}
**数据源 / Data Source**: FDA FAERS (openFDA public API)
**模板版本 / Template Version**: 1.0

---

## 一、Executive Summary / 概要

### 报告期间 / Reporting Period
{period}

### 信号统计 / Signal Statistics
- 新发现信号 / New Signals: {n_new}
- 已验证信号 / Validated Signals: {n_validated}
- 已关闭信号 / Closed Signals: {n_closed}
- 总计 / Total: {n_total}

### 行动总结 / Action Summary
{action_summary}

---

## 二、Signal Detection Methods / 信号检测方法

### 数据源 / Data Sources
- FDA FAERS (openFDA public REST API)
- 算法 / Algorithms: PRR / ROR / EBGM / IC

### 阈值 / Thresholds
- PRR ≥ 2 AND χ² ≥ 4
- ROR 95% CI lower bound > 1
- EBGM 95% CI lower bound (EB05) ≥ 2
- IC 95% CI lower bound (IC025) > 0

---

## 三、New Signals / 新发现信号

{new_signals_section}

---

## 四、Validated Signals / 已验证信号更新

{validated_signals_section}

---

## 五、Risk Characterization / 风险特征描述

{risk_characterization_section}

---

## 六、Benefit-Risk Assessment / 获益-风险评估

{benefit_risk_section}

---

## 七、Actions Taken / 已采取行动

{actions_section}

---

## 八、References / 方法学引用

1. CIOMS Working Group VIII. Practical Aspects of Signal Detection in Pharmacovigilance. 2010.
2. ICH E2C(R2) Periodic Benefit-Risk Evaluation Report. 2012.
3. FDA Guidance for Industry. Good Pharmacovigilance Practices and Pharmacoepidemiologic Assessment. 2005.
4. Evans SJ, Waller PC, Davis S. Use of proportional reporting ratios (PRRs) for signal generation from spontaneous adverse drug reaction reports. Pharmacoepidemiol Drug Saf. 2001;10(6):483-486.

---

*本报告由 ct-safety 自动生成，所有医学结论标注为"draft, requires medical review"。*
*This report was auto-generated by ct-safety. All medical conclusions are marked as "draft, requires medical review".*
"""


def generate_psur(signal_list: List[Dict], period: str, fmt: str = "md") -> str:
    """生成 PSUR 报告。
    
    参数：
        signal_list: 信号列表
        period: 报告期间
        fmt: 输出格式（md 或 json）
    """
    if fmt == "json":
        return json.dumps({
            "period": period,
            "generated_at": datetime.datetime.utcnow().isoformat(),
            "signal_count": len(signal_list),
            "signals": signal_list,
        }, ensure_ascii=False, indent=2)
    
    # 分类信号
    new_signals = [s for s in signal_list if s.get("status") == "new"]
    validated_signals = [s for s in signal_list if s.get("status") == "validated"]
    closed_signals = [s for s in signal_list if s.get("status") == "closed"]
    
    # 生成各节
    new_section = _generate_signal_table(new_signals) if new_signals else "（本报告期间无新发现信号）"
    validated_section = _generate_signal_table(validated_signals) if validated_signals else "（本报告期间无已验证信号更新）"
    risk_section = _generate_risk_section(signal_list)
    benefit_section = _generate_benefit_risk_section(signal_list)
    actions_section = _generate_actions_section(signal_list)
    
    action_summary = f"本报告期间共发现 {len(new_signals)} 个新信号，{len(validated_signals)} 个已验证信号更新。"
    
    return PSUR_TEMPLATE.format(
        period=period,
        generated_date=datetime.datetime.utcnow().strftime("%Y-%m-%d"),
        n_new=len(new_signals),
        n_validated=len(validated_signals),
        n_closed=len(closed_signals),
        n_total=len(signal_list),
        action_summary=action_summary,
        new_signals_section=new_section,
        validated_signals_section=validated_section,
        risk_characterization_section=risk_section,
        benefit_risk_section=benefit_section,
        actions_section=actions_section,
    )


def _generate_signal_table(signals: List[Dict]) -> str:
    """生成信号表格。"""
    lines = []
    lines.append("| 药物 Drug | 事件 Event | PRR | ROR | EBGM | 验证状态 | 行动建议 |")
    lines.append("|---|---|---|---|---|---|---|")
    
    for s in signals:
        lines.append(
            f"| {s.get('drug', '')} | {s.get('event', '')} | "
            f"{s.get('prr', '-')} | {s.get('ror', '-')} | {s.get('ebgm', '-')} | "
            f"{s.get('status', '')} | {s.get('action', '-')} |"
        )
    
    return "\n".join(lines)


def _generate_risk_section(signals: List[Dict]) -> str:
    """生成风险特征描述节。"""
    if not signals:
        return "（无信号数据）"
    
    # 按风险等级分组
    critical = [s for s in signals if s.get("risk_level") == "CRITICAL"]
    high = [s for s in signals if s.get("risk_level") == "HIGH"]
    medium = [s for s in signals if s.get("risk_level") == "MEDIUM"]
    low = [s for s in signals if s.get("risk_level") == "LOW"]
    
    lines = []
    if critical:
        lines.append(f"**严重风险信号 ({len(critical)})**: " + ", ".join(f"{s.get('drug')}+{s.get('event')}" for s in critical))
    if high:
        lines.append(f"**高风险信号 ({len(high)})**: " + ", ".join(f"{s.get('drug')}+{s.get('event')}" for s in high))
    if medium:
        lines.append(f"**中等风险信号 ({len(medium)})**: " + ", ".join(f"{s.get('drug')}+{s.get('event')}" for s in medium))
    if low:
        lines.append(f"**低风险信号 ({len(low)})**: " + ", ".join(f"{s.get('drug')}+{s.get('event')}" for s in low))
    
    return "\n".join(lines) if lines else "（无风险信号）"


def _generate_benefit_risk_section(signals: List[Dict]) -> str:
    """生成获益-风险评估节。"""
    return "（需结合临床数据、适应症、替代治疗方案综合评估）\n\n**注意**: 本节需医学专业人员填写。"


def _generate_actions_section(signals: List[Dict]) -> str:
    """生成已采取行动节。"""
    actions = []
    for s in signals:
        action = s.get("action_taken", "")
        if action:
            actions.append(f"- {s.get('drug')}+{s.get('event')}: {action}")
    
    if actions:
        return "\n".join(actions)
    return "（本报告期间未采取特殊行动）"


def main():
    p = argparse.ArgumentParser(description="PSUR/PBRER 报告生成")
    p.add_argument("--signals", type=str, default=None, help="信号列表 JSON 文件")
    p.add_argument("--period", type=str, required=True, help="报告期间（如 2025-Q1）")
    p.add_argument("--format", choices=["md", "json"], default="md", help="输出格式")
    p.add_argument("--output", type=str, default=None, help="输出文件路径")
    
    args = p.parse_args()
    
    signals = []
    if args.signals:
        with open(args.signals, "r", encoding="utf-8") as f:
            signals = json.load(f)
    
    report = generate_psur(signals, args.period, args.format)
    
    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(report)
        print(f"已写入: {args.output}")
    else:
        print(report)


if __name__ == "__main__":
    main()
